site_name: Jack Homan
repo_url: https://github.com/johnhoman
theme:
  icon:
    repo: fontawesome/brands/git-alt
  name: material
  palette: 
  - scheme: default
    toggle:
      icon: material/toggle-switch-off-outline 
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate 
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
plugins:
- search
- macros
markdown_extensions:
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.critic
- pymdownx.caret
- pymdownx.keys
- pymdownx.mark
- pymdownx.tilde
- admonition
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
nav:
- index.md
- Kubeflow:
  - kubeflow-profile-controller-iam-plugin.md
- Kubernetes:
  - kubernetes-webhook-python.md
extra_css:
- stylesheets/extra.css
